import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../", import.meta.url);
const read = (path) => readFile(new URL(path, root), "utf8");

test("registers the neutral comment-source route without changing existing routes", async () => {
  const [vite, page, entry] = await Promise.all([
    read("vite.config.js"),
    read("comment-source/index.html"),
    read("src/comment-source.jsx"),
  ]);

  assert.match(vite, /advice\/index\.html/);
  assert.match(vite, /judgment\/index\.html/);
  assert.match(vite, /ratings\/index\.html/);
  assert.match(vite, /comment-source\/index\.html/);
  assert.match(page, /<title>Online Research Study<\/title>/);
  assert.match(page, /\/src\/comment-source\.jsx/);
  assert.match(entry, /SourceDetectionTask/);
});

test("participant UI requests one five-comment assignment and one required rating", async () => {
  const client = await read("src/SourceDetectionTask.jsx");

  assert.match(client, /claim_source_detection_assignment/);
  assert.match(client, /submit_source_detection_payload/);
  assert.match(client, /assignment\.comments\.map/);
  assert.match(client, /comments\.length !== 5/);
  assert.match(client, /\[1, 2, 3, 4, 5, 6, 7\]/);
  assert.match(
    client,
    /How likely is it that these comments were generated by artificial intelligence \(e\.g\. ChatGPT\)\?/,
  );
  assert.match(
    client,
    /<strong>you will give one[\s\S]*generated by artificial intelligence<\/strong>/,
  );
  assert.match(client, /rating === null \|\| submissionState === "submitting"/);
  assert.doesNotMatch(client, /localStorage|sessionStorage|stimuli\.json|modelLabel/);
});

test("restores consent, a two-strike attention check, and clipboard blocking", async () => {
  const [client, consent, css] = await Promise.all([
    read("src/SourceDetectionTask.jsx"),
    read("src/source-consent.js"),
    read("src/source-detection.css"),
  ]);

  assert.match(consent, /Principal Investigator: William J\. Brady/);
  assert.match(consent, /IRB #: STU00218134/);
  assert.match(client, /Informed Consent/);
  assert.match(client, /Consent Confirmation/);
  assert.match(client, /record_source_detection_comprehension_failure/);
  assert.match(client, /nextAttempts >= 2/);
  assert.match(client, /This research session has ended after two incorrect answers/);
  for (const eventName of ["copy", "cut", "paste", "drop", "dragstart", "contextmenu"]) {
    assert.match(client, new RegExp(`"${eventName}"`));
  }
  assert.match(client, /window\.getSelection\(\)\?\.removeAllRanges\(\)/);
  assert.match(css, /user-select: none/);
});

test("uses Prolific identifiers, separates test records, and validates completion redirects", async () => {
  const client = await read("src/SourceDetectionTask.jsx");

  assert.match(client, /PROLIFIC_PID/);
  assert.match(client, /STUDY_ID/);
  assert.match(client, /SESSION_ID/);
  assert.match(client, /\^\(test\|preview\|qa\)\[-_\]/);
  assert.match(client, /p_is_test: isTestParticipant/);
  assert.match(client, /parsed\.hostname === "app\.prolific\.com"/);
  assert.match(client, /VITE_SOURCE_DETECTION_COMPLETION_CODE/);
});

test("formal SQL defines 20 quota cells, five slots per cell, and exact-cell replacement", async () => {
  const sql = await read("supabase_source_detection_formal.sql");

  assert.match(sql, /set active = \(pair_role = 'primary'\)/);
  assert.match(sql, /cross join \(values \('human'::text\), \('ai'::text\)\)/);
  assert.match(sql, /cross join generate_series\(1, 5\)/);
  assert.match(sql, /unique \(stimulus_id, condition, slot_index\)/);
  assert.match(sql, /pg_advisory_xact_lock/);
  assert.match(sql, /order by coalesce\(counts\.occupied_count, 0\) asc, random\(\)/);
  assert.match(sql, /review_source_detection_assignment/);
  assert.match(sql, /record_source_detection_comprehension_failure/);
  assert.match(sql, /comprehension_failures = comprehension_failures \+ 1/);
  assert.match(sql, /when comprehension_failures \+ 1 >= 2 then 'screened_out'/);
  assert.match(sql, /status in \('claimed', 'submitted', 'screened_out', 'excluded', 'abandoned'\)/);
  assert.match(sql, /set status = 'open',[\s\S]*assignment_id = null/);
  assert.match(sql, /source_detection_cell_progress/);
  assert.match(sql, /to service_role/);
});

test("a five-slot specification yields 50 Human and 50 AI valid responses", () => {
  const cells = [];
  for (let post = 1; post <= 10; post += 1) {
    for (const condition of ["human", "ai"]) {
      for (let slot = 1; slot <= 5; slot += 1) {
        cells.push({ post, condition, slot });
      }
    }
  }

  assert.equal(cells.length, 100);
  assert.equal(cells.filter((cell) => cell.condition === "human").length, 50);
  assert.equal(cells.filter((cell) => cell.condition === "ai").length, 50);
  for (let post = 1; post <= 10; post += 1) {
    assert.equal(cells.filter((cell) => cell.post === post).length, 10);
    assert.equal(
      cells.filter((cell) => cell.post === post && cell.condition === "human")
        .length,
      5,
    );
    assert.equal(
      cells.filter((cell) => cell.post === post && cell.condition === "ai")
        .length,
      5,
    );
  }
});
