import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../", import.meta.url);
const read = (path) => readFile(new URL(path, root), "utf8");

test("registers the neutral comment-source route without changing existing routes", async () => {
  const [vite, page, entry] = await Promise.all([
    read("vite.config.js"),
    read("comment-source/index.html"),
    read("src/comment-source.jsx"),
  ]);

  assert.match(vite, /advice\/index\.html/);
  assert.match(vite, /judgment\/index\.html/);
  assert.match(vite, /ratings\/index\.html/);
  assert.match(vite, /comment-source\/index\.html/);
  assert.match(page, /<title>Online Research Study<\/title>/);
  assert.match(page, /\/src\/comment-source\.jsx/);
  assert.match(entry, /SourceDetectionTask/);
});

test("participant UI requires two distinct five-comment items and two ratings", async () => {
  const client = await read("src/SourceDetectionTask.jsx");

  assert.match(client, /claim_source_detection_assignment/);
  assert.match(client, /submit_source_detection_payload/);
  assert.match(client, /assignment\.items\[currentItemIndex\]/);
  assert.match(client, /value\.items\.length !== 2/);
  assert.match(client, /value\.items\[0\]\.postId === value\.items\[1\]\.postId/);
  assert.match(client, /currentItem\.comments\.map/);
  assert.match(client, /comments\.length !== 5/);
  assert.match(client, /\[1, 2, 3, 4, 5, 6, 7\]/);
  assert.match(
    client,
    /How likely is it that these comments were generated by artificial intelligence \(e\.g\. ChatGPT\)\?/,
  );
  assert.match(
    client,
    /<strong>\s*you will give\s+one[\s\S]*generated by artificial intelligence<\/strong>/,
  );
  assert.match(client, /Question \{currentItemIndex \+ 1\} of 2/);
  assert.match(client, /ratings\.some\(\(value\) => value === null\)/);
  assert.match(client, /responses: assignment\.items\.map/);
  assert.match(client, /currentItemIndex === 0 \? continueToSecondItem : submitResponse/);
  assert.doesNotMatch(client, /localStorage|sessionStorage|stimuli\.json|modelLabel/);
});

test("restores consent, a two-strike attention check, and clipboard blocking", async () => {
  const [client, consent, css] = await Promise.all([
    read("src/SourceDetectionTask.jsx"),
    read("src/source-consent.js"),
    read("src/source-detection.css"),
  ]);

  assert.match(consent, /Principal Investigator: William J\. Brady/);
  assert.match(consent, /IRB #: STU00218134/);
  assert.match(client, /Informed Consent/);
  assert.match(client, /Consent Confirmation/);
  assert.match(client, /record_source_detection_comprehension_failure/);
  assert.match(client, /nextAttempts >= 2/);
  assert.match(client, /This research session has ended after two incorrect answers/);
  for (const eventName of ["copy", "cut", "paste", "drop", "dragstart", "contextmenu"]) {
    assert.match(client, new RegExp(`"${eventName}"`));
  }
  assert.match(client, /window\.getSelection\(\)\?\.removeAllRanges\(\)/);
  assert.match(css, /user-select: none/);
});

test("uses Prolific identifiers, separates test records, and validates completion redirects", async () => {
  const client = await read("src/SourceDetectionTask.jsx");

  assert.match(client, /PROLIFIC_PID/);
  assert.match(client, /STUDY_ID/);
  assert.match(client, /SESSION_ID/);
  assert.match(client, /\^\(test\|preview\|qa\)\[-_\]/);
  assert.match(client, /p_is_test: isTestParticipant/);
  assert.match(client, /parsed\.hostname === "app\.prolific\.com"/);
  assert.match(client, /VITE_SOURCE_DETECTION_COMPLETION_CODE/);
});

test("dual SQL defines 100 same-source participant slots and exact-slot replacement", async () => {
  const sql = await read("supabase_source_detection_dual.sql");

  assert.match(sql, /slot_index integer not null check \(slot_index between 1 and 50\)/);
  assert.match(sql, /check \(stimulus_id_1 <> stimulus_id_2\)/);
  assert.match(sql, /values \('human'::text\), \('ai'::text\)/);
  assert.match(sql, /assignment_version integer not null default 1/);
  assert.match(sql, /stimulus_id_2 text/);
  assert.match(sql, /rating_2 integer/);
  assert.match(sql, /Exactly two item responses are required/);
  assert.match(sql, /v_assignment\.condition = 'human'/);
  assert.match(sql, /pg_advisory_xact_lock/);
  assert.match(sql, /review_source_detection_assignment/);
  assert.match(sql, /record_source_detection_comprehension_failure/);
  assert.match(sql, /source_detection_dual_slots[\s\S]*set status = 'open', assignment_id = null/);
  assert.match(sql, /source_detection_cell_progress/);
  assert.match(sql, /source_detection_condition_progress/);
  assert.match(sql, /to service_role/);
});

test("the 50-slot schedule yields 10 ratings per post and condition", () => {
  const rounds = [
    [[1, 10], [2, 9], [3, 8], [4, 7], [5, 6]],
    [[1, 9], [10, 8], [2, 7], [3, 6], [4, 5]],
    [[1, 8], [9, 7], [10, 6], [2, 5], [3, 4]],
    [[1, 7], [8, 6], [9, 5], [10, 4], [2, 3]],
    [[1, 6], [7, 5], [8, 4], [9, 3], [10, 2]],
    [[1, 5], [6, 4], [7, 3], [8, 2], [9, 10]],
    [[1, 4], [5, 3], [6, 2], [7, 10], [8, 9]],
    [[1, 3], [4, 2], [5, 10], [6, 9], [7, 8]],
    [[1, 2], [3, 10], [4, 9], [5, 8], [6, 7]],
    [[1, 10], [2, 9], [3, 8], [4, 7], [5, 6]],
  ];
  const pairSlots = rounds.flat();
  const participants = ["human", "ai"].flatMap((condition) =>
    pairSlots.map((posts, index) => ({ condition, slot: index + 1, posts })),
  );

  assert.equal(pairSlots.length, 50);
  assert.equal(participants.length, 100);
  assert.equal(participants.filter(({ condition }) => condition === "human").length, 50);
  assert.equal(participants.filter(({ condition }) => condition === "ai").length, 50);
  assert.equal(participants.reduce((sum, participant) => sum + participant.posts.length, 0), 200);
  assert.ok(participants.every(({ posts }) => posts[0] !== posts[1]));

  for (const condition of ["human", "ai"]) {
    for (let post = 1; post <= 10; post += 1) {
      assert.equal(
        participants.filter(
          (participant) =>
            participant.condition === condition && participant.posts.includes(post),
        ).length,
        10,
      );
    }
  }
});
