import React, { useEffect, useMemo, useState } from "react";
import { INFORMED_CONSENT_TEXT } from "./source-consent";

const QUESTION =
  "How likely is it that these comments were generated by artificial intelligence (e.g. ChatGPT)?";
const PROLIFIC_COMPLETION_BASE_URL =
  "https://app.prolific.com/submissions/complete";
const CORRECT_COMPREHENSION = "rate-comment-source";

const useGlobalClipboardBlock = () => {
  useEffect(() => {
    const blockClipboard = (event) => {
      event.preventDefault();
      window.getSelection()?.removeAllRanges();
    };
    const blockedEvents = [
      "copy",
      "cut",
      "paste",
      "drop",
      "dragstart",
      "contextmenu",
    ];

    blockedEvents.forEach((eventName) => {
      document.addEventListener(eventName, blockClipboard, true);
    });
    return () => {
      blockedEvents.forEach((eventName) => {
        document.removeEventListener(eventName, blockClipboard, true);
      });
    };
  }, []);
};

const cleanParameter = (value) => {
  if (!value || value.includes("{{%") || value.includes("%}}")) return "";
  return value.trim();
};

const getQueryParams = () => new URLSearchParams(window.location.search);

const getParticipant = () => {
  const params = getQueryParams();
  return {
    prolificPid: cleanParameter(
      params.get("PROLIFIC_PID") || params.get("prolific_pid"),
    ),
    studyId: cleanParameter(params.get("STUDY_ID") || params.get("study_id")),
    sessionId: cleanParameter(
      params.get("SESSION_ID") || params.get("session_id"),
    ),
  };
};

const isTestParticipant = (prolificPid) =>
  /^(test|preview|qa)[-_]/i.test(prolificPid);

const getSupabaseConfig = () => {
  const url = String(import.meta.env.VITE_SUPABASE_URL || "")
    .trim()
    .replace(/\/$/, "");
  const anonKey = String(import.meta.env.VITE_SUPABASE_ANON_KEY || "").trim();
  if (!url || !anonKey) return null;
  return { url, anonKey };
};

const getProlificCompletion = () => {
  const params = getQueryParams();
  let code = cleanParameter(
    params.get("completion_code") ||
      params.get("COMPLETION_CODE") ||
      import.meta.env.VITE_SOURCE_DETECTION_COMPLETION_CODE,
  );
  const explicitUrl = cleanParameter(params.get("completion_url"));

  if (explicitUrl) {
    try {
      const parsed = new URL(explicitUrl);
      if (parsed.protocol === "https:" && parsed.hostname === "app.prolific.com") {
        code = code || cleanParameter(parsed.searchParams.get("cc"));
        return { code, url: parsed.toString() };
      }
    } catch {
      // Fall through to a completion-code URL or the neutral completion screen.
    }
  }

  if (code && /^[A-Za-z0-9_-]{3,80}$/.test(code)) {
    return {
      code,
      url: `${PROLIFIC_COMPLETION_BASE_URL}?cc=${encodeURIComponent(code)}`,
    };
  }
  return { code: "", url: "" };
};

const supabaseRpc = async (config, functionName, payload) => {
  const response = await fetch(`${config.url}/rest/v1/rpc/${functionName}`, {
    method: "POST",
    headers: {
      apikey: config.anonKey,
      Authorization: `Bearer ${config.anonKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(payload),
  });

  const text = await response.text();
  let data = null;
  try {
    data = text ? JSON.parse(text) : null;
  } catch {
    data = null;
  }

  if (!response.ok) {
    throw new Error(
      data?.message || `The study database returned HTTP ${response.status}.`,
    );
  }
  return data;
};

const validateAssignment = (value) => {
  if (
    !value ||
    !value.assignmentId ||
    !value.postId ||
    !value.postTitle ||
    !value.postBody
  ) {
    throw new Error("The assigned study material was incomplete.");
  }
  if (
    !Array.isArray(value.comments) ||
    value.comments.length !== 5 ||
    !Array.isArray(value.commentHashes) ||
    value.commentHashes.length !== 5 ||
    !Array.isArray(value.commentOrder) ||
    value.commentOrder.length !== 5
  ) {
    throw new Error("The assigned comment set failed its completeness check.");
  }
  if (value.comments.some((comment) => !String(comment).trim())) {
    throw new Error("The assigned comment set contained an empty comment.");
  }
  if (
    value.comments.some(
      (comment) => /[^\x09\x0a\x0d\x20-\x7e]/.test(String(comment)) || /[\\*]/.test(String(comment)),
    )
  ) {
    throw new Error("The assigned comment set was not fully cleaned.");
  }
};

const StudyHeader = ({ ready = false }) => (
  <header className="source-study-header">
    <div>
      <p className="source-institution">Northwestern University Research Study</p>
      <h1>Online Research Study</h1>
    </div>
    <div className="source-session-card" aria-label="Research session status">
      <strong>Research Session</strong>
      <span>{ready ? "Assignment ready" : "Preparing…"}</span>
    </div>
  </header>
);

const PrimaryButton = ({ children, disabled = false, onClick }) => (
  <button
    type="button"
    className="source-primary-button"
    disabled={disabled}
    onClick={onClick}
  >
    {children}
  </button>
);

const SecondaryButton = ({ children, onClick }) => (
  <button
    type="button"
    className="source-secondary-button"
    onClick={onClick}
  >
    {children}
  </button>
);

const ConsentText = () => (
  <div className="source-consent-text">{INFORMED_CONSENT_TEXT}</div>
);

export default function SourceDetectionTask() {
  useGlobalClipboardBlock();

  const [screen, setScreen] = useState("loading");
  const [assignment, setAssignment] = useState(null);
  const [agreed, setAgreed] = useState(false);
  const [comprehension, setComprehension] = useState("");
  const [comprehensionAttempts, setComprehensionAttempts] = useState(0);
  const [comprehensionError, setComprehensionError] = useState("");
  const [rating, setRating] = useState(null);
  const [error, setError] = useState("");
  const [startedAt, setStartedAt] = useState("");
  const [consentedAt, setConsentedAt] = useState("");
  const [instructionsOpenedAt, setInstructionsOpenedAt] = useState("");
  const [taskOpenedAt, setTaskOpenedAt] = useState("");
  const [submittedAt, setSubmittedAt] = useState("");
  const [submissionState, setSubmissionState] = useState("idle");
  const [submissionError, setSubmissionError] = useState("");
  const [alreadySubmitted, setAlreadySubmitted] = useState(false);
  const completion = useMemo(() => getProlificCompletion(), []);

  useEffect(() => {
    let active = true;
    const participant = getParticipant();
    const config = getSupabaseConfig();
    const params = getQueryParams();

    if (!participant.prolificPid) {
      setError(
        "Missing PROLIFIC_PID. Open this study from Prolific, or add PROLIFIC_PID=test-review-1 to the URL when reviewing it.",
      );
      setScreen("error");
      return () => {
        active = false;
      };
    }

    if (!config) {
      setError("The study database is not configured.");
      setScreen("error");
      return () => {
        active = false;
      };
    }

    supabaseRpc(config, "claim_source_detection_assignment", {
      p_prolific_pid: participant.prolificPid,
      p_study_id: participant.studyId || null,
      p_session_id: participant.sessionId || null,
      p_is_test: isTestParticipant(participant.prolificPid),
    })
      .then((response) => {
        if (!active) return;
        validateAssignment(response);
        const nextAssignment = {
          ...response,
          participant,
          config,
          debug:
            params.get("debug") === "1" &&
            isTestParticipant(participant.prolificPid),
        };
        setAssignment(nextAssignment);
        const failureCount = Number(response.comprehensionFailures) || 0;
        setComprehensionAttempts(failureCount);
        if (response.status === "screened_out" || failureCount >= 2) {
          setScreen("comprehension_failed");
        } else if (response.status === "submitted") {
          setAlreadySubmitted(true);
          setSubmittedAt(response.submittedAt || "");
          setScreen("complete");
        } else {
          setScreen("intro");
        }
      })
      .catch((loadError) => {
        if (!active) return;
        setError(
          loadError instanceof Error
            ? loadError.message
            : "The study could not be loaded.",
        );
        setScreen("error");
      });

    return () => {
      active = false;
    };
  }, []);

  const elapsedSeconds = useMemo(() => {
    if (!taskOpenedAt || !submittedAt) return null;
    return Math.max(
      0,
      Math.round(
        (new Date(submittedAt).getTime() - new Date(taskOpenedAt).getTime()) /
          1000,
      ),
    );
  }, [submittedAt, taskOpenedAt]);

  const beginStudy = () => {
    const now = new Date().toISOString();
    setStartedAt(now);
    setScreen("consent");
    window.scrollTo({ top: 0, behavior: "auto" });
  };

  const acceptConsent = () => {
    const now = new Date().toISOString();
    setConsentedAt(now);
    setInstructionsOpenedAt(now);
    setScreen("instructions");
    window.scrollTo({ top: 0, behavior: "auto" });
  };

  const beginTask = () => {
    setTaskOpenedAt(new Date().toISOString());
    setScreen("task");
    window.scrollTo({ top: 0, behavior: "auto" });
  };

  const handleComprehensionChange = async (value) => {
    if (!value) {
      setComprehension("");
      return;
    }
    if (value === CORRECT_COMPREHENSION) {
      setComprehension(value);
      setComprehensionError("");
      return;
    }

    setComprehension("");
    setComprehensionError("");
    try {
      const result = await supabaseRpc(
        assignment.config,
        "record_source_detection_comprehension_failure",
        {
          p_assignment_id: assignment.assignmentId,
          p_selected_option: value,
          p_payload: {
            participant: assignment.participant,
            selectedOption: value,
            occurredAt: new Date().toISOString(),
          },
        },
      );
      const nextAttempts =
        Number(result.comprehensionFailures) || comprehensionAttempts + 1;
      const screenedOut =
        Boolean(result.screenedOut) ||
        result.status === "screened_out" ||
        nextAttempts >= 2;

      setComprehensionAttempts(nextAttempts);
      setAssignment((current) => ({
        ...current,
        status: result.status || (screenedOut ? "screened_out" : current.status),
        comprehensionFailures: nextAttempts,
      }));

      if (screenedOut) {
        setScreen("comprehension_failed");
        window.scrollTo({ top: 0, behavior: "auto" });
        return;
      }

      setComprehensionError("Incorrect, please read the instructions and try again.");
      window.alert("Incorrect, please try again.");
    } catch {
      setComprehensionError(
        "We could not save the attention-check result. Please refresh and try again.",
      );
    }
  };

  const submitResponse = async () => {
    if (!assignment || rating === null || submissionState === "submitting") return;

    const now = new Date().toISOString();
    const payload = {
      schemaVersion: "source-detection-v3",
      status: "completed",
      submittedAt: now,
      participant: assignment.participant,
      assignment: {
        assignmentId: assignment.assignmentId,
        pairNumber: assignment.pairNumber,
        pairRole: assignment.pairRole,
        postId: assignment.postId,
        commentOrder: assignment.commentOrder,
        commentHashes: assignment.commentHashes,
        postBodySha256: assignment.postBodySha256,
      },
      response: {
        question: QUESTION,
        rating,
      },
      protocol: {
        consentConfirmed: Boolean(consentedAt),
        comprehensionPassed: comprehension === CORRECT_COMPREHENSION,
        priorComprehensionFailures: comprehensionAttempts,
      },
      prolificCompletion: {
        code: completion.code || null,
        returnUrlConfigured: Boolean(completion.url),
      },
      timing: {
        startedAt,
        consentedAt,
        instructionsOpenedAt,
        taskOpenedAt,
        submittedAt: now,
        responseTimeMs: Math.max(
          0,
          new Date(now).getTime() - new Date(taskOpenedAt).getTime(),
        ),
      },
    };

    setSubmissionState("submitting");
    setSubmissionError("");
    try {
      await supabaseRpc(
        assignment.config,
        "submit_source_detection_payload",
        {
          p_assignment_id: assignment.assignmentId,
          p_payload: payload,
        },
      );
      setSubmittedAt(now);
      setAlreadySubmitted(false);
      setScreen("complete");
      window.scrollTo({ top: 0, behavior: "auto" });
    } catch (submissionFailure) {
      setSubmissionState("error");
      setSubmissionError(
        submissionFailure instanceof Error
          ? submissionFailure.message
          : "Your response could not be saved.",
      );
    }
  };

  if (screen === "loading") {
    return (
      <main className="source-study-page source-centered-page">
        <div className="source-loading-card" role="status">
          <span className="source-loading-dot" />
          Preparing your assignment…
        </div>
      </main>
    );
  }

  if (screen === "error") {
    return (
      <main className="source-study-page">
        <div className="source-page-wrap source-narrow-wrap">
          <StudyHeader />
          <section className="source-panel source-error-panel" role="alert">
            <p className="source-eyebrow">Study unavailable</p>
            <h2>We could not prepare this research session.</h2>
            <p>{error}</p>
          </section>
        </div>
      </main>
    );
  }

  if (!assignment) return null;

  if (screen === "intro") {
    return (
      <main className="source-study-page">
        <div className="source-page-wrap source-narrow-wrap">
          <StudyHeader ready />
          <section className="source-panel source-intro-panel">
            <p className="source-eyebrow">Study overview</p>
            <h2>Read a short online discussion</h2>
            <p className="source-intro-copy">
              In this task, you will read one anonymous, public online post and
              one set of five comments about it. You will then answer one short
              question about those comments.
            </p>
            <div className="source-overview-grid">
              <div>
                <span>Task</span>
                <strong>1 post, 5 comments, and 1 judgment</strong>
              </div>
              <div>
                <span>Time</span>
                <strong>Most participants finish in about 5–7 minutes</strong>
              </div>
            </div>
            <div className="source-intro-action">
              <div>
                <h3>Session ready</h3>
                <p>
                  After consent and instructions, the task will open here. Your
                  assignment will remain the same if you refresh.
                </p>
              </div>
              <PrimaryButton onClick={beginStudy}>Begin Study</PrimaryButton>
            </div>
            {assignment.debug && (
              <div className="source-debug-note">
                Debug only · Assignment {assignment.assignmentId} · Pair{" "}
                {assignment.pairNumber} · {assignment.debugCondition || "source hidden"}
              </div>
            )}
          </section>
        </div>
      </main>
    );
  }

  if (screen === "consent") {
    return (
      <main className="source-study-page">
        <div className="source-page-wrap source-wide-wrap">
          <StudyHeader ready />
          <div className="source-consent-layout">
            <section className="source-panel source-consent-panel">
              <p className="source-eyebrow">Before you begin</p>
              <h2>Informed Consent</h2>
              <ConsentText />
            </section>
            <aside className="source-panel source-consent-confirmation">
              <h3>Consent Confirmation</h3>
              <label className="source-consent-checkbox">
                <input
                  type="checkbox"
                  checked={agreed}
                  onChange={(event) => setAgreed(event.target.checked)}
                />
                <span>
                  I have read and understood the information above. I am 18
                  years or older and voluntarily agree to participate.
                </span>
              </label>
              <div className="source-button-row">
                <SecondaryButton
                  onClick={() => {
                    setAgreed(false);
                    setScreen("declined");
                  }}
                >
                  I Disagree
                </SecondaryButton>
                <PrimaryButton disabled={!agreed} onClick={acceptConsent}>
                  I Agree
                </PrimaryButton>
              </div>
            </aside>
          </div>
        </div>
      </main>
    );
  }

  if (screen === "declined") {
    return (
      <main className="source-study-page">
        <div className="source-page-wrap source-narrow-wrap">
          <StudyHeader ready />
          <section className="source-panel source-completion-panel">
            <p className="source-eyebrow">Participation declined</p>
            <h2>You have chosen not to participate.</h2>
            <p>
              You may close this browser window or return to the crowdsourcing
              platform. No response has been submitted.
            </p>
            <SecondaryButton onClick={() => setScreen("consent")}>
              Back to Consent
            </SecondaryButton>
          </section>
        </div>
      </main>
    );
  }

  if (screen === "instructions") {
    return (
      <main className="source-study-page">
        <div className="source-page-wrap source-wide-wrap">
          <StudyHeader ready />
          <div className="source-consent-layout source-instructions-layout">
            <section className="source-panel source-consent-panel">
              <p className="source-eyebrow">Task preparation</p>
              <h2>Instructions</h2>
              <div className="source-instructions-copy">
                <p>
                  You will read one anonymous public online post about a social
                  dilemma and a set of five comments responding to that post.
                </p>
                <p>
                  After reading all five comments, <strong>you will give one
                  overall rating of how likely it is that the comments were
                  generated by artificial intelligence</strong>. Rate the five
                  comments as a group, rather than rating each comment
                  separately.
                </p>
                <p>
                  Please rely on your own judgment. Do not use outside tools,
                  and do not copy or paste text from the study.
                </p>
              </div>
            </section>
            <aside className="source-panel source-consent-confirmation">
              <label className="source-check-label" htmlFor="source-check">
                Attention check
              </label>
              <p className="source-check-copy">
                To make sure the instructions are clear, select what you will
                be doing in this task:
              </p>
              <select
                id="source-check"
                value={comprehension}
                onChange={(event) =>
                  handleComprehensionChange(event.target.value)
                }
                className="source-check-select"
              >
                <option value="">Select the correct statement</option>
                <option value="rate-post-source">
                  I will judge whether the online post itself was written by AI.
                </option>
                <option value="rate-each-comment">
                  I will give a separate AI rating to each of the five comments.
                </option>
                <option value={CORRECT_COMPREHENSION}>
                  I will read one post and five comments, then give one overall
                  AI-likelihood rating for the comments.
                </option>
                <option value="write-advice">
                  I will write advice to the person who created the post.
                </option>
              </select>
              <p className="source-attempt-note">
                Two incorrect answers end the study. Incorrect answers so far: {" "}
                {comprehensionAttempts}.
              </p>
              {comprehensionError && (
                <p className="source-inline-error" role="alert">
                  {comprehensionError}
                </p>
              )}
              <div className="source-button-row">
                <SecondaryButton onClick={() => setScreen("consent")}>
                  Back
                </SecondaryButton>
                <PrimaryButton
                  disabled={comprehension !== CORRECT_COMPREHENSION}
                  onClick={beginTask}
                >
                  Start Task
                </PrimaryButton>
              </div>
            </aside>
          </div>
        </div>
      </main>
    );
  }

  if (screen === "comprehension_failed") {
    return (
      <main className="source-study-page">
        <div className="source-page-wrap source-narrow-wrap">
          <StudyHeader ready />
          <section className="source-panel source-error-panel">
            <p className="source-eyebrow">Study ended</p>
            <h2>You did not pass the attention check.</h2>
            <p>
              This research session has ended after two incorrect answers.
              Please return to the platform. No completion code is available,
              and this participant ID cannot restart the study.
            </p>
            {assignment.debug && (
              <div className="source-debug-note">
                Debug only · Assignment {assignment.assignmentId} · screened out
              </div>
            )}
          </section>
        </div>
      </main>
    );
  }

  if (screen === "complete") {
    return (
      <main className="source-study-page">
        <div className="source-page-wrap source-narrow-wrap">
          <StudyHeader ready />
          <section className="source-panel source-completion-panel">
            <div className="source-completion-mark" aria-hidden="true">
              ✓
            </div>
            <p className="source-eyebrow">Response recorded</p>
            <h2>
              {alreadySubmitted
                ? "This research session has already been completed."
                : "Study Complete"}
            </h2>
            <p>
              {completion.url
                ? "Your response has been submitted. Please click the button below to return to Prolific and complete your submission."
                : alreadySubmitted
                  ? "Your original assignment and submitted response remain securely recorded."
                  : "Your response has been securely saved. This link does not include a Prolific completion code."}
            </p>
            {!alreadySubmitted && elapsedSeconds !== null && (
              <p className="source-completion-meta">
                Completion time: {elapsedSeconds} seconds
              </p>
            )}
            {completion.url && (
              <>
                <PrimaryButton
                  onClick={() => window.location.assign(completion.url)}
                >
                  Return to Prolific
                </PrimaryButton>
                <p className="source-completion-help">
                  If the button does not work, return to Prolific manually and
                  enter this completion code:
                </p>
                <div className="source-completion-code-card">
                  <span>Completion Code</span>
                  <strong>{completion.code}</strong>
                </div>
              </>
            )}
            {assignment.debug && (
              <div className="source-debug-note">
                Debug only · Assignment {assignment.assignmentId} · Pair{" "}
                {assignment.pairNumber} · {assignment.debugCondition || "source hidden"}
              </div>
            )}
          </section>
        </div>
      </main>
    );
  }

  return (
    <main className="source-study-page">
      <div className="source-page-wrap source-wide-wrap">
        <StudyHeader ready />
        <div className="source-task-heading">
          <div>
            <p className="source-eyebrow">Comment evaluation</p>
            <h2>Read the post and comments carefully</h2>
          </div>
          <span>1 of 1</span>
        </div>

        <div className="source-stimulus-grid">
          <section className="source-panel source-post-panel">
            <div className="source-panel-heading">
              <p className="source-eyebrow">Online post</p>
              <h3>{assignment.postTitle}</h3>
            </div>
            <div className="source-text source-post-text">
              {assignment.postBody}
            </div>
          </section>

          <section className="source-panel source-comments-panel">
            <div className="source-comments-heading">
              <div>
                <p className="source-eyebrow">Anonymous discussion</p>
                <h3>Comments</h3>
              </div>
              <span>5 comments</span>
            </div>
            <p className="source-comments-instruction">
              Please read all five comments before answering the question below.
            </p>
            <div className="source-comment-feed">
              {assignment.comments.map((comment, index) => (
                <article
                  className="source-comment-card"
                  key={assignment.commentHashes[index]}
                >
                  <div>Comment {index + 1}</div>
                  <p>{comment}</p>
                </article>
              ))}
            </div>
          </section>
        </div>

        <section className="source-panel source-rating-panel">
          <p className="source-eyebrow">Question 1</p>
          <fieldset>
            <legend>{QUESTION}</legend>
            <div className="source-rating-options">
              {[1, 2, 3, 4, 5, 6, 7].map((score) => (
                <label
                  className={
                    rating === score
                      ? "source-rating-option selected"
                      : "source-rating-option"
                  }
                  key={score}
                >
                  <input
                    type="radio"
                    name="ai-likelihood"
                    value={score}
                    checked={rating === score}
                    onChange={() => {
                      setRating(score);
                      setSubmissionError("");
                      setSubmissionState("idle");
                    }}
                  />
                  <span>{score}</span>
                </label>
              ))}
            </div>
            <div className="source-rating-anchors" aria-hidden="true">
              <span>
                <b>1</b> — Not at all likely
              </span>
              <span>
                <b>4</b> — Somewhat likely
              </span>
              <span>
                <b>7</b> — Very likely
              </span>
            </div>
          </fieldset>
          <div className="source-submit-row">
            <div>
              <p>
                {rating === null
                  ? "Select one response to continue."
                  : `Response selected: ${rating}`}
              </p>
              {submissionError && (
                <p className="source-submission-error" role="alert">
                  {submissionError}
                </p>
              )}
            </div>
            <PrimaryButton
              disabled={rating === null || submissionState === "submitting"}
              onClick={submitResponse}
            >
              {submissionState === "submitting"
                ? "Saving…"
                : "Submit response"}
            </PrimaryButton>
          </div>
        </section>

        {assignment.debug && (
          <aside className="source-debug-note source-debug-fixed">
            Debug only · Assignment {assignment.assignmentId} · Pair{" "}
            {assignment.pairNumber} · {assignment.debugCondition || "source hidden"} · order{" "}
            {assignment.commentOrder.join("-")}
          </aside>
        )}
      </div>
    </main>
  );
}
